ANSWERED = [
    {"name": "Porozumění uměleckému textu", "answered": [range(35, 36), range(40, 51)]},
    {"name": "Porozumění neuměleckému textu", "answered": [range(1, 15)]},
    {"name": "Práce s definicí", "answered": []},
    {"name": "Práce s obrázky a textem", "answered": []},
    {"name": "Textová návaznost", "answered": []},
    {"name": "Sloh", "answered": []},
    {"name": "Pravidla českého pravopisu: uzavřené úlohy", "answered": [range(1, 6), range(10, 15), 59, 63, 87, 103, 122]},
    {"name": "Pravidla českého pravopisu: otevřené úlohy", "answered": []},
    {"name": "Význam slov a významové vztahy", "answered": []},
    {"name": "Citově zabarvená slova, spisovnost × nespisovnost", "answered": [1, 2, range(6, 11)]},
    {"name": "Ustálená slovní spojení", "answered": []},
    {"name": "Hlásky a stavba slov", "answered": []},
    {"name": "Slova příbuzná", "answered": []},
    {"name": "Základní skladební dvojice", "answered": [range(1, 6)]},
    {"name": "Výstavba věty jednoduché a souvětí", "answered": []},
    {"name": "Přímá × nepřímá řeč", "answered": []},
    {"name": "Slovní druhy", "answered": []},
    {"name": "Mluvnické kategorie", "answered": []},
    {"name": "Tvary slov", "answered": []},
    {"name": "Literatura", "answered": []},
    {"name": "Číslo a početní operace", "answered": [range(1, 6), range(10, 14), range(18, 21), 32, 35, 60, 73,]},
    {"name": "Slovní úlohy na číslo a početní operace", "answered": [range(1, 46), 109, 110, 151, 152]},
    {"name": "Převody jednotek", "answered": [range(1, 6), 7, 8, 17, 18, 31, 36, 42]},   
    {"name": "Grafy, schémata, tabulky a slovní úlohy s nimi", "answered": [range(35, 38), 50, 51, 59, 63, 64]},
    {"name": "Geometrie v rovině", "answered": []},
    {"name": "Geometrie v prostoru", "answered": [range(1, 6), range(7, 16)]},
    {"name": "Konstrukční úlohy", "answered": [range(1, 6)]},
    {"name": "Aplikační úlohy netypicky zadané", "answered": [14, 15, ]},
    {"name": "Osová souměrnost", "answered": [range(3, 6), 9]},
]
