CATEGORIES = [
    {"name": "Porozumění uměleckému textu", "category": "radio_1", "subject": "cj"},
    {"name": "Porozumění neuměleckému textu","category":"radio_2", "subject": "cj"},
    {"name": "Práce s definicí","category":"radio_3", "subject": "cj"},
    {"name": "Práce s obrázky a textem","category":"radio_4", "subject": "cj"},
    {"name": "Textová návaznost","category":"radio_5", "subject": "cj"},
    {"name": "Sloh","category":"radio_6", "subject": "cj"},
    {"name": "Pravidla českého pravopisu: uzavřené úlohy","category":"radio_7", "subject": "cj"},
    {"name": "Pravidla českého pravopisu: otevřené úlohy","category":"radio_8", "subject": "cj"},
    {"name": "Význam slov a významové vztahy","category":"radio_9", "subject": "cj"},
    {"name": "Citově zabarvená slova, spisovnost × nespisovnost","category":"radio_10", "subject": "cj"},
    {"name": "Ustálená slovní spojení","category":"radio_11", "subject": "cj"},
    {"name": "Hlásky a stavba slov","category":"radio_12", "subject": "cj"},
    {"name": "Slova příbuzná","category":"radio_13", "subject": "cj"},
    {"name": "Základní skladební dvojice","category":"radio_14", "subject": "cj"},
    {"name": "Výstavba věty jednoduché a souvětí","category":"radio_15", "subject": "cj"},
    {"name": "Přímá × nepřímá řeč","category":"radio_16", "subject": "cj"},
    {"name": "Slovní druhy","category":"radio_17", "subject": "cj"},
    {"name": "Mluvnické kategorie","category":"radio_18", "subject": "cj"},
    {"name": "Tvary slov","category":"radio_19", "subject": "cj"},
    {"name": "Literatura","category":"radio_20", "subject": "cj"},
    {"name": "Číslo a početní operace", "category": "radio_2", "subject": "ma"},
    {"name": "Slovní úlohy na číslo a početní operace", "category": "radio_3", "subject": "ma"},
    {"name": "Převody jednotek", "category": "radio_4", "subject": "ma"},
    {"name": "Grafy, schémata, tabulky a slovní úlohy s nimi", "category": "radio_5", "subject": "ma"},
    {"name": "Geometrie v rovině", "category": "radio_6", "subject": "ma"},
    {"name": "Geometrie v prostoru", "category": "radio_7", "subject": "ma"},
    {"name": "Konstrukční úlohy", "category": "radio_8", "subject": "ma"},
    {"name": "Aplikační úlohy netypicky zadané", "category": "radio_9", "subject": "ma"},
    {"name": "Osová souměrnost", "category": "radio_10", "subject": "ma"},
]
