python scrape.py --subject cj --category radio_1 --detect-total
python scrape.py --subject cj --category radio_2 --detect-total
python scrape.py --subject cj --category radio_3 --detect-total
python scrape.py --subject cj --category radio_4 --detect-total
python scrape.py --subject cj --category radio_5 --detect-total
python scrape.py --subject cj --category radio_6 --detect-total
python scrape.py --subject cj --category radio_7 --detect-total
python scrape.py --subject cj --category radio_8 --detect-total
python scrape.py --subject cj --category radio_9 --detect-total
python scrape.py --subject cj --category radio_10 --detect-total
python scrape.py --subject cj --category radio_11 --detect-total
python scrape.py --subject cj --category radio_12 --detect-total
python scrape.py --subject cj --category radio_13 --detect-total
python scrape.py --subject cj --category radio_14 --detect-total
python scrape.py --subject cj --category radio_15 --detect-total
python scrape.py --subject cj --category radio_16 --detect-total
python scrape.py --subject cj --category radio_17 --detect-total
python scrape.py --subject cj --category radio_18 --detect-total
python scrape.py --subject cj --category radio_19 --detect-total
python scrape.py --subject cj --category radio_20 --detect-total

python scrape.py --subject ma --category radio_2 --detect-total
python scrape.py --subject ma --category radio_3 --detect-total
python scrape.py --subject ma --category radio_4 --detect-total
python scrape.py --subject ma --category radio_5 --detect-total
python scrape.py --subject ma --category radio_6 --detect-total
python scrape.py --subject ma --category radio_7 --detect-total
python scrape.py --subject ma --category radio_8 --detect-total
python scrape.py --subject ma --category radio_9 --detect-total
python scrape.py --subject ma --category radio_10 --detect-total